const express = require('express');
const authController = require('../controllers/admin/authController');
const submissionsController = require('../controllers/admin/submissionsController');
const eventsController = require('../controllers/admin/eventsController');
const academyController = require('../controllers/admin/academyController');
const { adminUrl } = require('../config/adminPath');
const { requireAuth, requireRole } = require('../middleware/auth');
const { loginLimiter } = require('../middleware/rateLimiter');

const router = express.Router();

router.get('/login', authController.showLogin);
router.post('/login', loginLimiter, authController.login);
router.post('/logout', requireAuth, authController.logout);
router.get('/', requireAuth, (request, response) => response.redirect(adminUrl('/submissions')));
router.get('/submissions', requireAuth, submissionsController.index);
router.post('/submissions/export', requireAuth, submissionsController.exportCsv);
router.post('/submissions/export/mailerlite', requireAuth, submissionsController.exportMailerLiteCsv);
router.get('/submissions/new', requireAuth, submissionsController.newForm);
router.post('/submissions/new', requireAuth, submissionsController.create);
router.get('/submissions/:id/edit', requireAuth, submissionsController.editForm);
router.post('/submissions/:id/edit', requireAuth, submissionsController.update);
router.post('/submissions/:id/delete', requireAuth, submissionsController.destroy);
router.get('/submissions/:id', requireAuth, submissionsController.redirectToEdit);
router.get('/events', requireAuth, eventsController.index);
router.get('/events/new', requireAuth, eventsController.newForm);
router.post('/events/new', requireAuth, eventsController.create);
router.get('/events/:id/edit', requireAuth, eventsController.editForm);
router.post('/events/:id/edit', requireAuth, eventsController.update);
router.post('/events/:id/delete', requireAuth, eventsController.destroy);
router.get('/academy/courses', requireAuth, academyController.coursesIndex);
router.get('/academy/courses/new', requireAuth, academyController.newCourse);
router.post('/academy/courses/new', requireAuth, academyController.createCourse);
router.get('/academy/courses/:id/edit', requireAuth, academyController.editCourse);
router.post('/academy/courses/:id/edit', requireAuth, academyController.updateCourse);
router.post('/academy/courses/:id/delete', requireAuth, academyController.deleteCourse);
router.get('/academy/courses/:courseId/lessons', requireAuth, academyController.lessonsIndex);
router.get('/academy/courses/:courseId/lessons/new', requireAuth, academyController.newLesson);
router.post('/academy/courses/:courseId/lessons/new', requireAuth, academyController.createLesson);
router.get('/academy/lessons/:id/edit', requireAuth, academyController.editLesson);
router.post('/academy/lessons/:id/edit', requireAuth, academyController.updateLesson);
router.post('/academy/lessons/:id/delete', requireAuth, academyController.deleteLesson);
router.get('/academy/access', requireAuth, academyController.accessIndex);
router.post('/academy/access', requireAuth, academyController.grantAccess);
router.post('/academy/access/:userId/:courseId/revoke', requireAuth, academyController.revokeAccess);
router.get('/academy/users', requireAuth, academyController.usersIndex);
router.post('/academy/users/:id/deactivate', requireRole('superadmin'), academyController.deactivateUser);

module.exports = router;
