const express = require('express');
const authController = require('../controllers/admin/authController');
const submissionsController = require('../controllers/admin/submissionsController');
const eventsController = require('../controllers/admin/eventsController');
const academyController = require('../controllers/admin/academyController');
const mediatorsController = require('../controllers/admin/mediatorsController');
const { adminUrl } = require('../config/adminPath');
const { requireAuth, requireRole } = require('../middleware/auth');
const { loginLimiter, sensitiveActionLimiter } = require('../middleware/rateLimiter');

const filesController = require('../controllers/admin/filesController');
const { rateLimit } = require('express-rate-limit');
const router = express.Router();
const uploadLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 100, standardHeaders: true, legacyHeaders: false, message: { success: false, message: 'Zbyt wiele uploadów. Spróbuj później.' } });
router.post('/files', filesController.requireFileAdmin, uploadLimiter, filesController.create);
router.get('/files/:id/download', filesController.requireFileAdmin, filesController.download);
router.delete('/files/:id', filesController.requireFileAdmin, filesController.remove);
router.use('/academy', (request, response, next) => request.method === 'POST' ? filesController.requireFileAdmin(request, response, next) : next());

router.get('/login', authController.showLogin);
router.post('/login', loginLimiter, authController.login);
router.use((request, response, next) => request.method === 'POST' ? sensitiveActionLimiter(request, response, next) : next());
router.post('/logout', requireAuth, authController.logout);
router.get('/', requireAuth, (request, response) => response.redirect(adminUrl('/submissions')));
router.get('/submissions', requireAuth, submissionsController.index);
router.post('/submissions/export', requireAuth, submissionsController.exportCsv);
router.post('/submissions/export/mailerlite', requireAuth, submissionsController.exportMailerLiteCsv);
router.get('/submissions/new', requireAuth, submissionsController.newForm);
router.post('/submissions/new', requireAuth, submissionsController.create);
router.get('/submissions/:id/edit', requireAuth, submissionsController.editForm);
router.post('/submissions/:id/edit', requireAuth, submissionsController.update);
router.post('/submissions/:id/delete', requireAuth, submissionsController.destroy);
router.get('/submissions/:id', requireAuth, submissionsController.redirectToEdit);
router.get('/events', requireAuth, eventsController.index);
router.get('/events/new', requireAuth, eventsController.newForm);
router.post('/events/new', requireAuth, eventsController.create);
router.get('/events/:id/edit', requireAuth, eventsController.editForm);
router.post('/events/:id/edit', requireAuth, eventsController.update);
router.post('/events/:id/delete', requireAuth, eventsController.destroy);
router.get('/mediators', requireAuth, mediatorsController.index);
router.get('/mediators/new', requireAuth, mediatorsController.newForm);
router.post('/mediators/new', requireAuth, mediatorsController.create);
router.get('/mediators/:id/edit', requireAuth, mediatorsController.editForm);
router.post('/mediators/:id/edit', requireAuth, mediatorsController.update);
router.post('/mediators/:id/delete', requireAuth, mediatorsController.destroy);
router.get('/academy/workspace', requireAuth, academyController.workspace);
router.get('/academy/workspace/data', requireAuth, academyController.workspaceDataEndpoint);
router.post('/academy/workspace/order', requireAuth, academyController.reorderWorkspace);
router.get('/academy/courses', requireAuth, academyController.coursesIndex);
router.get('/academy/orders', requireAuth, academyController.ordersIndex);
router.get('/academy/orders/:id', requireAuth, academyController.orderDetail);
router.post('/academy/orders/:id/refund', requireRole('superadmin'), academyController.requestOrderRefund);
router.get('/academy/courses/new', requireAuth, academyController.newCourse);
router.post('/academy/courses/new', requireAuth, academyController.createCourse);
router.get('/academy/courses/:id/edit', requireAuth, academyController.editCourse);
router.post('/academy/courses/:id/edit', requireAuth, academyController.updateCourse);
router.post('/academy/courses/:id/delete', requireAuth, academyController.deleteCourse);
router.get('/academy/courses/:courseId/modules', requireAuth, academyController.modulesIndex);
router.get('/academy/courses/:courseId/modules/new', requireAuth, academyController.newModule);
router.post('/academy/courses/:courseId/modules/new', requireAuth, academyController.createModule);
router.get('/academy/modules/:id/edit', requireAuth, academyController.editModule);
router.post('/academy/modules/:id/edit', requireAuth, academyController.updateModule);
router.post('/academy/modules/:id/delete', requireAuth, academyController.deleteModule);
router.get('/academy/modules/:moduleId/lessons', requireAuth, academyController.moduleLessonsIndex);
router.get('/academy/modules/:moduleId/lessons/new', requireAuth, academyController.newModuleLesson);
router.post('/academy/modules/:moduleId/lessons/new', requireAuth, academyController.createModuleLesson);
router.get('/academy/courses/:courseId/lessons', requireAuth, academyController.lessonsIndex);
router.get('/academy/courses/:courseId/lessons/new', requireAuth, academyController.newLesson);
router.post('/academy/courses/:courseId/lessons/new', requireAuth, academyController.createLesson);
router.get('/academy/lessons/:id/edit', requireAuth, academyController.editLesson);
router.post('/academy/lessons/:id/edit', requireAuth, academyController.updateLesson);
router.post('/academy/lessons/:id/delete', requireAuth, academyController.deleteLesson);
router.get('/academy/access', requireAuth, academyController.accessIndex);
router.post('/academy/access', requireAuth, academyController.grantAccess);
router.post('/academy/access/:userId/:courseId/revoke', requireAuth, academyController.revokeAccess);
router.get('/academy/users', requireAuth, academyController.usersIndex);
router.post('/academy/users/:id/deactivate', requireRole('superadmin'), academyController.deactivateUser);

module.exports = router;
