const express = require('express');
const mediationController = require('../controllers/public/mediationController');
const mediatorController = require('../controllers/public/mediatorController');
const submitController = require('../controllers/public/submitController');
const authController = require('../controllers/public/authController');
const accountController = require('../controllers/public/accountController');
const academyController = require('../controllers/public/academyController');
const paymentController = require('../controllers/public/paymentController');
const youtubeController = require('../controllers/public/youtubeController');
const { registrationDomainLimiter, registrationEmailLimiter, registrationGlobalLimiter, registrationLimiter, sensitiveActionLimiter, submitLimiter, verificationResendLimiter } = require('../middleware/rateLimiter');
const { loginValidation, mediationCaseValidation, mediatorApplicationValidation, passwordChangeValidation, registrationValidation, resetValidation, submitValidation } = require('../middleware/validate');
const { loginLimiter } = require('../middleware/rateLimiter');
const { requireUser, requireUserApi } = require('../middleware/userAuth');
const chatController = require('../controllers/public/chatController');
const { accountBillingValidation, accountProfileValidation, authenticatedPasswordChangeValidation, deleteAccountValidation } = require('../middleware/validate');

const router = express.Router();
const fileDownloadLimiter = require('express-rate-limit').rateLimit({ windowMs: 60000, limit: 60, keyGenerator: request => String(request.session.user.id), standardHeaders: true, legacyHeaders: false, message: { success: false, message: 'Zbyt wiele pobrań. Spróbuj za minutę.' } });
router.get('/api/academy/attachments/:id/download', requireUserApi, fileDownloadLimiter, require('../controllers/public/filesController').download);
router.get('/api/chats/:uuid/messages', requireUserApi, chatController.history);

router.post('/api/submit', submitLimiter, submitValidation, submitController.store);
router.get('/api/auth/registration-settings', authController.registrationSettings);
router.post('/api/auth/register', registrationGlobalLimiter, registrationLimiter, registrationEmailLimiter, registrationDomainLimiter, registrationValidation, authController.register);
router.post('/api/auth/resend-verification', verificationResendLimiter, registrationValidation, authController.resendVerification);
router.post('/api/auth/login', loginLimiter, loginValidation, authController.login);
router.post('/api/auth/logout', sensitiveActionLimiter, authController.logout);
router.get('/api/auth/session', authController.sessionInfo);
router.get('/api/auth/account', requireUser, accountController.getAccount);
router.get('/api/auth/account/orders', requireUser, accountController.getOrders);
router.get('/api/auth/account/export', requireUser, accountController.exportAccount);
router.put('/api/auth/account/profile', sensitiveActionLimiter, requireUser, accountProfileValidation, accountController.updateProfile);
router.put('/api/auth/account/billing', sensitiveActionLimiter, requireUser, accountBillingValidation, accountController.updateBilling);
router.post('/api/auth/account/password', sensitiveActionLimiter, requireUser, authenticatedPasswordChangeValidation, accountController.changePassword);
router.delete('/api/auth/account', sensitiveActionLimiter, requireUser, deleteAccountValidation, accountController.deleteAccount);
router.get('/api/academy/courses', requireUserApi, academyController.listCourses);
router.get('/api/academy/catalog', requireUserApi, academyController.listCatalog);
router.get('/api/academy/courses/:slug', requireUserApi, academyController.showCourse);
router.get('/api/academy/courses/:slug/modules/:moduleSlug', requireUserApi, academyController.showModule);
router.get('/api/academy/courses/:slug/modules/:moduleSlug/lessons/:lessonSlug', requireUserApi, academyController.showModuleLesson);
router.get('/api/academy/courses/:slug/lessons/:lessonSlug', requireUserApi, academyController.showLesson);
router.post('/api/academy/lessons/:id/progress', sensitiveActionLimiter, requireUserApi, academyController.updateLessonProgress);
router.post('/api/academy/orders', sensitiveActionLimiter, requireUserApi, paymentController.createOrder);
router.post('/api/payments/webhook/przelewy24/refund', paymentController.webhook);
router.post('/api/payments/webhook/:provider', paymentController.webhook);
router.post('/api/auth/verify-email', loginLimiter, authController.verifyEmail);
router.post('/api/auth/password-reset', loginLimiter, resetValidation, authController.requestPasswordReset);
router.post('/api/auth/password-reset/confirm', loginLimiter, passwordChangeValidation, authController.resetPassword);
router.post('/api/mediacje/zgloszenie', submitLimiter, mediationCaseValidation, mediationController.submitCase);
router.get('/api/mediacje/mediatorzy', mediatorController.listPublished);
router.post('/api/mediacje/zostan-mediatorem', submitLimiter, mediatorApplicationValidation, mediatorController.submitApplication);
router.get('/youtube/:videoId', youtubeController.show);

module.exports = router;
