<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
function respond(int $code,bool $ok,string $message):never{http_response_code($code);echo json_encode(['success'=>$ok,'message'=>$message],JSON_UNESCAPED_UNICODE);exit;}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')respond(405,false,'Dozwolona jest wyłącznie metoda POST.');
if(!empty($_POST['website']??''))respond(200,true,'Zgłoszenie zostało przyjęte.');
if(time()-(int)($_POST['form-started']??0)<3)respond(422,false,'Formularz został wysłany zbyt szybko. Spróbuj ponownie.');
$rate=sys_get_temp_dir().'/pb-form-'.hash('sha256',(string)($_SERVER['REMOTE_ADDR']??'unknown'));if(is_file($rate)&&time()-(int)filemtime($rate)<60)respond(429,false,'Kolejne zgłoszenie możesz wysłać za chwilę.');
$allowedRoles=['Generalny wykonawca','Wykonawca','Podwykonawca','Dostawca materiałów','Producent materiałów','Inżynier, projektant lub architekt','Usługodawca dla budownictwa','Inna'];$allowedSizes=['1–2 osoby','3–10 osób','11–50 osób','51–250 osób','Powyżej 250 osób'];
$roles=array_values(array_unique(array_filter(array_map('strval',is_array($_POST['role']??null)?$_POST['role']:[]),fn($v)=>in_array($v,$allowedRoles,true))));
$f=['name'=>trim((string)($_POST['name']??'')),'company'=>trim((string)($_POST['company']??'')),'email'=>trim((string)($_POST['email']??'')),'phone'=>trim((string)($_POST['phone']??'')),'company-size'=>trim((string)($_POST['company-size']??''))];
foreach(['name','company','email','company-size']as $x)if($f[$x]==='')respond(422,false,'Uzupełnij wszystkie wymagane pola.');if(!$roles)respond(422,false,'Wybierz co najmniej jedną rolę w branży.');if(!in_array($f['company-size'],$allowedSizes,true))respond(422,false,'Wybierz poprawną wielkość firmy.');if(empty($_POST['consent-service'])||empty($_POST['consent-marketing']))respond(422,false,'Wymagane zgody muszą zostać zaznaczone.');if(!filter_var($f['email'],FILTER_VALIDATE_EMAIL)||preg_match('/[\r\n]/',$f['email']))respond(422,false,'Podaj poprawny adres e-mail.');foreach($f as $v)if(mb_strlen($v)>250)respond(422,false,'Jedno z pól jest zbyt długie.');
$admin="Nowe zgłoszenie z formularza polskiebudownictwo.org\n\nImię i nazwisko: {$f['name']}\nFirma: {$f['company']}\nE-mail: {$f['email']}\nTelefon: ".($f['phone']?:'Nie podano')."\nRole: ".implode(', ',$roles)."\nWielkość firmy: {$f['company-size']}\nZgoda marketingowa: Tak";
$url='https://polskiebudownictwo.org/assets/documents/legal/manifestMSP.pdf';$subject='Dołączasz do inicjatywy Polskie Budownictwo. Przeczytaj manifest i przekaż go dalej';
$text="Dziękujemy, że dołączasz do społeczności Polskie Budownictwo.\n\nW polskiej branży budowlanej zbyt wiele dobrych firm płaci wysoką cenę za nierówne warunki współpracy, ryzykowne zapisy umów i brak szacunku dla polskiego kapitału. Nie musi tak być.\n\nRusza inicjatywa, która łączy wykonawców, podwykonawców, dostawców, architektów i inżynierów wokół jednego celu: bezpieczniejszego, uczciwszego rynku, na którym rozwój firmy nie oznacza strachu o jej przyszłość.\n\nManifest Polskiego Budownictwa wyznacza kierunek wspólnego działania. Przeczytaj go i pomóż nam dotrzeć do przedsiębiorców, którzy również powinni zabrać głos.\n\nPrzeczytaj Manifest Polskiego Budownictwa:\n{$url}\n\nSiła tej inicjatywy zależy od ludzi z branży. Prześlij tę wiadomość przedsiębiorcy, który powinien o tym wiedzieć.\n\nDziękujemy, że budujesz tę inicjatywę razem z nami.";
$logoUrl='https://polskiebudownictwo.org/assets/images/logo.png';
$html='<!doctype html><html lang="pl"><body style="margin:0;background:#f4f4f4;font-family:Arial,sans-serif;color:#202020"><div style="max-width:640px;margin:auto;background:#fff;padding:32px"><p style="margin:0 0 28px"><a href="https://polskiebudownictwo.org/" style="text-decoration:none"><img src="'.$logoUrl.'" width="220" alt="Polskie Budownictwo" style="display:block;width:220px;max-width:100%;height:auto;border:0"></a></p><h1>Dziękujemy, że dołączasz do Polskiego Budownictwa.</h1><p>W polskiej branży budowlanej zbyt wiele dobrych firm płaci wysoką cenę za nierówne warunki współpracy, ryzykowne zapisy umów i brak szacunku dla polskiego kapitału. Nie musi tak być.</p><p>Rusza inicjatywa, która łączy wykonawców, podwykonawców, dostawców, architektów i inżynierów wokół jednego celu: bezpieczniejszego, uczciwszego rynku, na którym rozwój firmy nie oznacza strachu o jej przyszłość.</p><p>Manifest Polskiego Budownictwa wyznacza kierunek wspólnego działania. Przeczytaj go i pomóż nam dotrzeć do przedsiębiorców, którzy również powinni zabrać głos.</p><p><a href="'.$url.'" style="display:inline-block;padding:15px 20px;background:#ee2329;color:#fff;text-decoration:none;font-weight:bold">Przeczytaj Manifest Polskiego Budownictwa</a></p><p>Siła tej inicjatywy zależy od ludzi z branży.</p><p><a href="mailto:?subject='.rawurlencode($subject).'&body='.rawurlencode($text).'" style="display:inline-block;padding:15px 20px;border:2px solid #ee2329;color:#202020;text-decoration:none;font-weight:bold">Prześlij tę wiadomość przedsiębiorcy, który powinien o tym wiedzieć</a></p><p>Dziękujemy, że budujesz tę inicjatywę razem z nami.</p></div></body></html>';
require_once __DIR__.'/smtp-mailer.php';$cfg=require __DIR__.'/smtp-config.php';try{smtpSend($cfg,'kontakt@polskiebudownictwo.org',$f['email'],'Nowe zgłoszenie - Polskie Budownictwo',$admin);smtpSend($cfg,$f['email'],'kontakt@polskiebudownictwo.org',$subject,$text,$html);@touch($rate);}catch(Throwable $e){error_log('Formularz SMTP: '.$e->getMessage());respond(500,false,'Nie udało się wysłać zgłoszenia. Spróbuj ponownie później.');}
respond(200,true,'Dziękujemy za dołączenie. Wiadomość z manifestem została wysłana na podany adres e-mail.');
